import{a as b,S,i as s}from"./assets/vendor-Dy2ZTtfi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const a of o)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function e(o){const a={};return o.integrity&&(a.integrity=o.integrity),o.referrerPolicy&&(a.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?a.credentials="include":o.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(o){if(o.ep)return;o.ep=!0;const a=e(o);fetch(o.href,a)}})();const w="https://pixabay.com/api/",q="50787945-1edbab8bb6a94afd781f3e3fd";function u(t,r=1){return b(w,{params:{key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}}).then(n=>n.data)}const m=document.querySelector(".gallery");let v=new S(".gallery a",{captionsData:"alt",captionDelay:300});function f(t){const r=t.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${e.likes}</p>
          <p class="info-item"><b>Views</b> ${e.views}</p>
          <p class="info-item"><b>Comments</b> ${e.comments}</p>
          <p class="info-item"><b>Downloads</b> ${e.downloads}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",r),v.refresh()}function M(){m.innerHTML=""}function h(){document.querySelector(".loader").classList.remove("is-hidden")}function y(){document.querySelector(".loader").classList.add("is-hidden")}function p(){document.querySelector(".load-more").classList.remove("hidden")}function c(){document.querySelector(".load-more").classList.add("hidden")}function g(){document.querySelector(".loader-add").classList.remove("hidden")}function L(){document.querySelector(".loader-add").classList.add("hidden")}const B=document.querySelector(".form"),P=document.querySelector(".load-more");document.querySelector(".loader-add");let d="",i=1;B.addEventListener("submit",R);P.addEventListener("click",$);async function R(t){t.preventDefault();const r=t.target.elements.query.value.trim();if(!r){s.error({message:"Please enter a search query",position:"topRight"});return}d=r,i=1;try{h(),c(),g(),M();const e=await u(d,i);if(e.hits.length===0){s.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}f(e.hits),e.totalHits>15&&p()}catch{s.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y(),L()}t.target.reset()}async function $(){i+=1;try{h(),c(),g();const t=await u(d,i);f(t.hits);const r=document.querySelector(".gallery-item"),{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"});const n=Math.ceil(t.totalHits/15);i>=n?(c(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):p()}catch{s.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y(),L()}}
//# sourceMappingURL=index.js.map
