import{a as w,S,i}from"./assets/vendor-Dy2ZTtfi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const a of o)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function e(o){const a={};return o.integrity&&(a.integrity=o.integrity),o.referrerPolicy&&(a.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?a.credentials="include":o.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(o){if(o.ep)return;o.ep=!0;const a=e(o);fetch(o.href,a)}})();const q="https://pixabay.com/api/",M="50787945-1edbab8bb6a94afd781f3e3fd";async function m(t,r=1){return(await w(q,{params:{key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}const f=document.querySelector(".gallery");let v=new S(".gallery a",{captionsData:"alt",captionDelay:300});function h(t){const r=t.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${e.likes}</p>
          <p class="info-item"><b>Views</b> ${e.views}</p>
          <p class="info-item"><b>Comments</b> ${e.comments}</p>
          <p class="info-item"><b>Downloads</b> ${e.downloads}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",r),v.refresh()}function P(){f.innerHTML=""}function y(){document.querySelector(".loader").classList.remove("is-hidden")}function p(){document.querySelector(".loader").classList.add("is-hidden")}function g(){document.querySelector(".load-more").classList.remove("hidden")}function c(){document.querySelector(".load-more").classList.add("hidden")}function L(){document.querySelector(".loader-add").classList.remove("hidden")}function b(){document.querySelector(".loader-add").classList.add("hidden")}const B=document.querySelector(".form"),R=document.querySelector(".load-more");document.querySelector(".loader-add");let d="",s=1,u=0;B.addEventListener("submit",$);R.addEventListener("click",A);async function $(t){t.preventDefault();const r=t.target.elements.query.value.trim();if(!r){i.error({message:"Please enter a search query",position:"topRight"});return}d=r,s=1;try{y(),c(),L(),P();const e=await m(d,s);if(console.log(e),e.hits.length===0){i.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(e.hits),console.log(e.hits),u=Math.ceil(e.totalHits/15),s<u&&g()}catch{i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p(),b()}t.target.reset()}async function A(){s+=1;try{y(),c(),L();const t=await m(d,s);h(t.hits);const r=document.querySelector(".gallery-item"),{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"});const n=Math.ceil(t.totalHits/15);s>=n?(c(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):g()}catch{i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p(),b()}}
//# sourceMappingURL=index.js.map
