import{a as b,S as L,i as n}from"./assets/vendor-Dy2ZTtfi.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))l(o);new MutationObserver(o=>{for(const a of o)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function e(o){const a={};return o.integrity&&(a.integrity=o.integrity),o.referrerPolicy&&(a.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?a.credentials="include":o.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(o){if(o.ep)return;o.ep=!0;const a=e(o);fetch(o.href,a)}})();const w="https://pixabay.com/api/",S="50787945-1edbab8bb6a94afd781f3e3fd";async function f(t,r=1){return(await b(w,{params:{key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})).data}const m=document.querySelector(".gallery");let q=new L(".gallery a",{captionsData:"alt",captionDelay:300});function h(t){const r=t.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${e.likes}</p>
          <p class="info-item"><b>Views</b> ${e.views}</p>
          <p class="info-item"><b>Comments</b> ${e.comments}</p>
          <p class="info-item"><b>Downloads</b> ${e.downloads}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",r),q.refresh()}function M(){m.innerHTML=""}function p(){document.querySelector(".loader").classList.remove("is-hidden")}function y(){document.querySelector(".loader").classList.add("is-hidden")}function g(){document.querySelector(".load-more").classList.remove("hidden")}function d(){document.querySelector(".load-more").classList.add("hidden")}const v=document.querySelector(".form"),B=document.querySelector(".load-more");let u="",s=1,i=0;v.addEventListener("submit",P);B.addEventListener("click",R);async function P(t){t.preventDefault();const r=t.target.elements.query.value.trim();if(!r){n.error({message:"Please enter a search query",position:"topRight"});return}u=r,s=1;try{p(),d(),M();const e=await f(u,s);if(console.log(e),e.hits.length===0){n.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(e.hits),console.log(e.hits),i=Math.ceil(e.totalHits/15),s<i&&g()}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}t.target.reset()}async function R(){s+=1;try{p(),d();const t=await f(u,s);h(t.hits);const r=document.querySelector(".gallery-item"),{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"}),i=Math.ceil(t.totalHits/15),s>=i?(d(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):g()}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}}
//# sourceMappingURL=index.js.map
